name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # specify the Go version

      - name: Build macOS ARM binary
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o gepetto-mac-arm-${GITHUB_REF##*/} gepetto.go

      - name: Build macOS Intel binary
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o gepetto-mac-intel-${GITHUB_REF##*/} gepetto.go

      - name: Build Linux Intel binary
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o gepetto-linux-intel-${GITHUB_REF##*/} gepetto.go

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o gepetto-windows-${GITHUB_REF##*/}.exe gepetto.go

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload macOS ARM binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-mac-arm-${GITHUB_REF##*/}
          asset_name: gepetto-mac-arm-${GITHUB_REF##*/}
          asset_content_type: application/octet-stream

      - name: Upload macOS Intel binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-mac-intel-${GITHUB_REF##*/}
          asset_name: gepetto-mac-intel-${GITHUB_REF##*/}
          asset_content_type: application/octet-stream

      - name: Upload Linux Intel binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-linux-intel-${GITHUB_REF##*/}
          asset_name: gepetto-linux-intel-${GITHUB_REF##*/}
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-windows-${GITHUB_REF##*/}.exe
          asset_name: gepetto-windows-${GITHUB_REF##*/}.exe
          asset_content_type: application/octet-stream
